spring:
  application:
    name: rabbit-spring

  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: ShaoJie
    password: 123456
    virtual-host: /test
#   简写上述的连接
#    addresses:

server:
  port: 8090